// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvcBPU8aBrJ3cwzw9skWANgQh30mBcS-w',
    appId: '1:222131529292:web:52d998f63fa82857d8f6e9',
    messagingSenderId: '222131529292',
    projectId: 'fir-auth-5380a',
    authDomain: 'fir-auth-5380a.firebaseapp.com',
    storageBucket: 'fir-auth-5380a.firebasestorage.app',
    measurementId: 'G-N737RG3Q6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd6IX1RyrWpmijuaNkJENT9toZDGFy6PQ',
    appId: '1:222131529292:android:aa642de786a31426d8f6e9',
    messagingSenderId: '222131529292',
    projectId: 'fir-auth-5380a',
    storageBucket: 'fir-auth-5380a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvcBPU8aBrJ3cwzw9skWANgQh30mBcS-w',
    appId: '1:222131529292:web:79e523802ec296eed8f6e9',
    messagingSenderId: '222131529292',
    projectId: 'fir-auth-5380a',
    authDomain: 'fir-auth-5380a.firebaseapp.com',
    storageBucket: 'fir-auth-5380a.firebasestorage.app',
    measurementId: 'G-NFF9GWGSFR',
  );
}
